// Pickup lines database
export interface PickupLineDatabase {
  [category: string]: string[];
}

export const pickupLines: PickupLineDatabase = {
  funny: [
    "Are you a parking ticket? Because you've got 'fine' written all over you.",
    "Are you from Tennessee? Because you're the only 10 I see!",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Do you like raisins? How about a date?",
    "Are you a bank loan? Because you have my interest.",
    "Are you Siri? Because you autocomplete me.",
    "Are you a charger? Because I'm dying without you. ",
    "Wanna be Minecraft without the craft? ",
    "Are you lighnting? Because you're McQueen. ",
    "Is there an airport nearby or is that my heart taking off? ",
    "Do you have a pet? Because seeing you has given me a whole new leash on life.",
    "Is your name Jimmy? Because I've Fallon for you. ",
    "I don't normally chase people but for you I'd put my crocs in sport mode. ",
    "Are you a Mariah Carey song? Because All I Want for Christmas Is You. ",
    "Aren't you worried about global warming? Because you're making it hot in here.",
    "If you were a triangle you'd be acute one.",
    "Are you a loan? You've got my interest.",
    "Are you a magician? Because when I look at you, everyone else disappears.",
    "Did you invent the airplane? Because you're clearly Mr. Wright.",
    "Is your dad a boxer? Because you're a knockout!",
    "How can I plan our wedding without having your number?",
    "Are you a keyboard? Because you might just be my type.",
    "You know, I'm actually terrible at flirting. How about you try to pick me up instead?",
  ],
  smooth: [
    "Your hand looks heavy. Let me hold it for you.",
    "I was feeling a bit off today, but you definitely turned me on.",
    "I must be a snowflake, because I've fallen for you.",
    "I'd say God bless you, but it looks like he already did.",
    "Can I follow you? Because my mom told me to follow my dreams.",
    "4+4=8 but you+me=fate",
    "Are you tired? You've been running through my mind all day. ",
    "What's your favorite drink? I'm asking so I know what to buy you when we go on our first date.",
    "I should complain to Spotify for not making you this week's hottest single. ",
    "Do you play soccer? Because you're a keeper. ",
    "You look so familiar…did we have class together? I could've sworn we had chemistry. ",
    "I'm learning about important dates in history, wanna be one of them?",
    "They say dating is a numbers game, so can I get yours?",
    "When I text you good morning tomorrow, what number should I text?",
    "Hi, my name is [your name], but you can call me tomorrow.",
    "Can I show your profile to my friends to prove that angels really do exist?",
    "There's something wrong with my phone, it doesn't have your number in it.",
  ],
  clever: [
    "Are you a compiler? Because you're raising my temperature.",
    "Are you HTTP? Because without you, I'm just ://",
    "You must be the square root of -1, because you can't be real and you're complex.",
    "Are you a 90-degree angle? Because you're looking right.",
    "Are you made of beryllium, gold, and titanium? Because you are Be-Au-Ti-ful.",
    "123456789. The only number I don't see here is yours. ",
    "Do you have Instagram? My parents always told me to follow my dreams. ",
    "Are you an artist? You're really good at drawing me in. ",
    "Angels should be in heaven. How'd you escape? ",
    "If you and I were socks, we'd make a great pair.",
    "Well, here I am! What are your other two wishes?",
    "Your name must be Barbie because when I saw you I pictured our Dreamhouse.",
    "What is it like to be the most gorgeous person in this room?",
    "If you were words on a page, you'd be fine print.",
    "You must be a talented thief because you managed to steal my heart from all the way over here.",
  ],
  cute: [
    "If you were a fruit, you'd be a fine-apple.",
    "Are you a dictionary? Because you add meaning to my life.",
    "You know what's on the menu? Me-n-u.",
    "I'm not an organ donor, but I'd be happy to give you my heart.",
    "Is your name Wifi? Because I'm feeling a connection.",
    "They say nothing lasts forever. Want to be my nothing? ",
    "Anyone who says Disney is the happiest place on earth has never stood next to you. ",
    "Are you a time traveler? Because I can see you in my future. ",
    "I'm not a photographer but I can picture you and me together. ",
    "Are you French? Because Eiffel for you. ",
    "Guess what I'm wearing? The smile you gave me.",
    "Are your parents bakers? Because you're a cutie pie.",
    "I had a good pickup line ready to go, but you're so good-looking I'm literally speechless.",
    "I think there's something wrong with my phone. Could you call it and see if it works?",
    "Did the sun come out, or did you just smile at me?",
    "Would you mind giving me a pinch? You're so cute, I must be dreaming.",
    "If I had a time machine, I'd use it to relive this exact moment. ",
  ],
  cheesy: [
    "Did the sun come out or did you just smile at me?",
    "If you were a triangle, you'd be acute one.",
    "Do you know what my shirt is made of? Boyfriend/girlfriend material.",
    "I'm no mathematician, but I'm pretty good with numbers. Tell you what, give me yours and watch what I can do with it.",
    "Is your dad a baker? Because you're a cutie pie!",
    "If I could rearrange the alphabet, I'd put U and I together. ",
    "What do you call a string of people lifting a mozzarella cheese? A cheesy pickup line.",
    "Are your shoelaces tied? I don't want you falling for anyone else.",
    `Are you a parking ticket? Because you've got "fine" written all over you.\t`,
    "On a scale of 1 to 10, you're a 9…because I'm the 1 you need. ",
    "Do you believe in love at first sight or should I walk by again? ",
    "Are you a cat? Because I've fallen fur you. ",
    "I'm not very good at math but I can give you the value you deserve. ",
    "I'm no electrician but I can light up your day. ",
    "Are you Google? You have everything I search for.",
    "Want a raisin? No? How about a date? ",
    "Are you from Tennessee? Because you're the only 10 I see.",
    "Want to go outside and get some fresh air with me? You just took my breath away.",
    "I can't tell if that was an earthquake, or if you just seriously rocked my world.",
    "Are you a dentist? My smile got brighter when I saw you.",
    "Do you know what the Little Mermaid and I have in common? We both want to be part of your world.",
  ],
  sexy: [
    "You can delete the app now, I'm here.",
    "Do you have a name? Or can I call you mine?",
    "There must be something wrong with my eyes—I can't seem to take them off of you.",
    "My name is [your name] but you should hear my phone number.",
    "Your lips look lonely. Would they like to meet mine?",
    "I'm not currently an organ donor, but I'd love to give you my heart.",
    "If you let me borrow a kiss, I promise I'll give it right back.",
    "Is it hot in here or is it just you?",
    "If I told you I like your body, would you hold it against me?",
    "My lips are getting jealous of all the words coming out of your mouth. They want to meet yours.",
    "Was your father a boxer? Because you're a knockout!",
    "You must be tired because you've been running through my mind all night.",
  ],
  flirty: [
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "I must be a snowflake, because I've fallen for you.",
    "I was blinded by your beauty... I'm going to need your name and phone number for insurance purposes.",
    "Can I take your picture? I want to show Santa what I want for Christmas.",
    "Feel my shirt. Know what it's made of? Boyfriend/girlfriend material.",
    "I'd like to take you to the movies but they don't let you bring your own snacks in. ",
    "No pen, no paper but you still draw my attention. ",
    "All the good pick up lines are taken but you aren't. ",
    "Excuse me while I delete my dating apps.",
    "This must be a museum because you're a work of art. ",
    "Are you WiFi? Because I feel a connection. ",
    "I'm not even playing cards but somehow I pulled a Queen. ",
    "You must be a dog person because you look fetching.",
    "I didn't even have to run to catch these butterflies. ",
    "I'm lost. Can you give me directions to your heart?",
    "Well, here I am. What are your other two wishes?",
    "Hey, how was heaven when you left it?",
    "I have a phone number, you have a phone number—think of the possibilities.",
    "I've got all these forks and knives all I need is a little spoon.",
    "Your hand looks heavy, can I hold it for you? ",
    'I always thought happiness started with an "H" but it looks like it starts with "U."',
    "Do you have a map? I just got lost in your eyes. ",
    "Did you just come out of an oven? Because you're too hot to handle.",
    "I think we've met before. Actually, never mind—I think it was just in my dreams.",
    "I bet my number sounds nicer than yours. Wanna hear it?",
    "Trust me, I'm not drunk—I'm just intoxicated by you.",
    "Do you have a mirror? Because I can see us together. ",
  ],
  corny: [
    "Do you like bacon? Wanna strip?",
    "Did you invent the airplane? Because you seem Wright for me.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "I'm not drunk, I'm just intoxicated by you.",
    "Is your name Ariel? Because we mermaid for each other.",
    "I hope someone knows how to do CPR because you just took my breath away. ",
    "You're looking a little sick, you must be suffering from lack of Vitamin Me. ",
    "Are you a WiFi router? Because I'm feeling a connection. ",
    "Do you have a Band-Aid? I scraped my knees falling for you.",
    "If you were a transformer you'd be Optimus Fine. ",
    "Let's play a game…not hide and seek though, people like you are hard to find.",
    "Do you like Star Wars? Because Yoda one for me. ",
    "I never believed in love at first sight, then I saw you. ",
    "It's a good thing I have my library card, because I am totally checking you out.",
    "If being beautiful was a crime, you'd be guilty as charged.",
    "My mom told me not to talk to strangers online, but I'll make an exception for you.",
    "Did you go to school at Hogwarts? Because I'm feeling the magic.",
    "I'm really glad I just bought life insurance because when I saw you, my heart stopped.",
    "If you were a vegetable, you'd be a cute-cumber.",
  ],
  database: [
    "Are you SQL? Because you structure my query language.",
    "Is your name MySQL? Because you've got lots of tables but all I want is to join with you.",
    "Are you a database? Because you have all the data I'm searching for.",
    "SELECT * FROM dating WHERE dating.their_number = your number;",
    "Are you MongoDB? Because I want to NoSQL, just one-on-one time with you.",

    "Are you a database query? Because you’ve been running through my mind all day.",
    "Are you a table? Because you complete the schema of my life.",
    "Are you SQL? Because you make my heart do SELECT * FROM feelings.",
    "Are you a primary key? Because you’re the unique identifier of my happiness.",
    "Are you a database administrator? Because you make my system run smoothly.",
    "Are you NoSQL? Because you’re unconventional, but I still want to work with you.",
    "Are you a stored procedure? Because you’ve got me executing all sorts of commands.",
    "Are you a foreign key? Because you’ve got a reference to my heart.",
    "Are you ACID compliant? Because you maintain the integrity of my emotions.",
    "Are you MongoDB? Because you’re document-oriented, and I’m documenting our love story.",
    "Are you a relational database? Because I want to join my life with yours.",
    "Are you a database index? Because you speed up my search for love.",
    "Are you Oracle? Because you’re the future I’ve been querying.",
    "Are you a database backup? Because you’re my safety net in this unpredictable world.",
    "Are you SQL injection? Because you inject excitement into my life.",
    "Are you a database trigger? Because you set off a cascade of emotions in me.",
    "Are you a data analyst? Because you make sense out of the chaos in my heart.",
    "Are you a data warehouse? Because you store all the memories I cherish.",
    "Are you a database replication? Because I want to duplicate this connection forever.",
    "Are you SQL Server? Because you’re the engine that keeps my love running.",
    "Are you a database query? Because you’ve perfectly sorted my priorities.",
    "Are you SQL? Because you make my heart do complex joins and unions.",
    "Are you a primary key? Because you’re the key to unlocking my happiness.",
    "Are you a relational database? Because I feel a strong connection with you.",
    "Are you NoSQL? Because you’re unconventional, but I’m drawn to your uniqueness.",
    "Are you a database administrator? Because you mana…eep everything in my life organized.",
    "Are you a stored procedure? Because you have a methodical way of handling everything.",
    "Are you a foreign key? Because you complement me in ways I never knew I needed.",
    "Are you ACID compliant? Because you’re the stability in my ever-changing world.",
    "Are you MongoDB? Because you’re flexible and adaptable, just like my feelings for you.",
    "Are you a database index? Because you make searching for love effortless.",
    "Are you Oracle? Because you foresee a bright future for us together.",
    "Are you a database backup? Because you’re my safety net in this unpredictable journey.",
    "Are you SQL injection? Because you inject excitement and passion into my life.",
    "Are you a database trigger? Because you ignite a cascade of emotions within me.",
    "Are you a data analyst? Because you help me understand the complexities of my heart.",
    "Are you a data warehouse? Because you store all th…cious memories of our time together.",
    "Are you a database replication? Because I want to multiply our love and happiness.",
    "Are you SQL Server? Because you’re the reliable foundation of our relationship.",
    "Are you a schema? Because you define the structure of my dreams and aspirations.",
    "Are you a database query? Because you’ve been running through my mind all day.",
    "Are you SQL? Because you make my heart do complex joins and unions.",
    "Are you a primary key? Because you’re the key to unlocking my happiness.",
    "Are you a relational database? Because I feel a strong connection with you.",
    "Are you NoSQL? Because you’re unconventional, but I’m drawn to your uniqueness.",
    "Are you a database administrator? Because you mana…eep everything in my life organized.",
    "Are you a stored procedure? Because you have a methodical way of handling everything.",
    "Are you a foreign key? Because you complement me in ways I never knew I needed.",
    "Are you ACID compliant? Because you’re the stability in my ever-changing world.",
    "Are you MongoDB? Because you’re flexible and adaptable, just like my feelings for you.",
    "Are you a database index? Because you make searching for love effortless.",
    "Are you Oracle? Because you foresee a bright future for us together.",
    "Are you a database backup? Because you’re my safety net in this unpredictable journey.",
    "Are you SQL injection? Because you inject excitement and passion into my life.",
    "Are you a database trigger? Because you ignite a cascade of emotions within me.",
    "Are you a data analyst? Because you help me understand the complexities of my heart.",
    "Are you a data warehouse? Because you store all th…cious memories of our time together.",
    "Are you a database replication? Because I want to multiply our love and happiness.",
    "Are you SQL Server? Because you’re the reliable foundation of our relationship.",
    "Are you a schema? Because you define the structure of my dreams and aspirations.",
    "Are you a SQL query? Because you’ve SELECTed my attention.",
    "Are you a database table? Because you’ve got all the fields I’m looking for.",
    "Are you NoSQL? Because you’re breaking the mold, and I’m intrigued.",
    "Are you a primary key? Because you’re the main ingredient in my relational schema.",
    "Are you MongoDB? Because you’re document-oriented, and I’m documenting my love for you.",
    "Are you SQL injection? Because you’ve injected excitement into my structured life.",
    "Are you a database administrator? Because you’ve optimized my heart’s performance.",
    "Are you a foreign key? Because you’re the missing piece in my referential integrity.",
    "Are you ACID compliant? Because you ensure the tra…f my emotions are always consistent.",
    "Are you a database index? Because you’ve sped up my search for true love.",
    "Are you a relational database? Because you’re making all the right connections with me.",
    "Are you Oracle? Because you’ve revealed the future of our relationship.",
    "Are you a stored procedure? Because you’ve executed a function in my heart.",
    "Are you a database backup? Because you’ve saved me from a life without you.",
    "Are you SQL Server? Because you’re the engine that’s powering my affection.",
    "Are you a database replication? Because I want our…e to propagate across all instances.",
    "Are you a schema? Because you’ve structured my dreams with your presence.",
    "Are you a data analyst? Because you’ve analyzed and found the perfect match in me.",
    "Are you a data warehouse? Because you contain all the valuable memories I hold dear.",
    "Are you Big Data? Because you’ve expanded my heart’s capacity for love.",
    "Are you a database query? Because you’ve got my heart racing with your unique results.",
    "Are you an SQL table? Because you’ve captured all my fields of interest.",
    "Do you believe in love at first join? Because I th…some great relational compatibility.",
    "Are you a database administrator? Because you’ve g…ight permissions to access my heart.",
    "Are you a NoSQL database? Because you’ve got that …that’s perfect for our relationship.",
    "Is your name Google? Because you’ve got everything…ve been searching for in a database.",
    "Are you SQL? Because you’ve got the queries that make my heart skip a beat.",
    "Are you a database backup? Because I never want to lose all the data we’ve shared.",
    "Are you MongoDB? Because you’ve got a document sto…of affection waiting to be explored.",
    "Are you Oracle? Because you’ve got the foresight to predict we’d make a perfect match.",
    "Are you MySQL? Because you’ve managed to store all my affectionate memories.",
    "Are you PostgreSQL? Because you’re open-source wit…our feelings, and that’s attractive.",
    "Are you a data warehouse? Because you’ve got all t…storage space for our infinite love.",
    "Are you a database trigger? Because just thinking about you sets off all my emotions.",
    "Are you Hadoop? Because you’ve got the scalability to handle all my love and affection.",
    "Are you a database constraint? Because you’ve managed to keep my heart in check.",
    "Are you SQL injection? Because you’ve injected excitement and passion into my life.",
    "Are you a foreign key? Because you’ve linked my he… to yours in the most beautiful way.",
    "Are you a database index? Because you’ve optimized the path to my heart.",
    "Are you a database transaction? Because every inte…ith you leaves me feeling fulfilled.",
    "Are you a database? Because whenever I see you, my heart starts indexing.",
    "Are you a SQL query? Because you’ve been running through my mind all day.",
    "Are you a table? Because you’ve got all the right attributes.",
    "Are you ACID compliant? Because you’ve got all the qualities I’m looking for.",
    "Are you a foreign key? Because you complete me.",
    "Are you NoSQL? Because you’re unconventional but I’m drawn to you.",
    "Are you a stored procedure? Because you make my life easier.",
    "Are you a database administrator? Because you manage to keep my heart in check.",
    "Are you a relational database? Because I want to join with you forever.",
    "Are you MongoDB? Because you handle my unstructured data with ease.",
    "Are you a clustered index? Because I want to be close to you.",
    "Are you a primary key? Because you’re the most important thing in my life.",
    "Are you a query optimizer? Because you make everything run smoothly.",
    "Are you SQL injection? Because every time I see you, you make my heart skip a beat.",
    "Are you a deadlock? Because you’ve got me stuck in a loop.",
    "Are you a data scientist? Because you know how to analyze my feelings.",
    "Are you a database schema? Because you give structure to my life.",
    "Are you a backup? Because you’re my safety net.",
    "Are you a transaction? Because I never want to rollback from you.",
    "Are you a relational model? Because I’m drawn to your connections.",
    "Are you a database query? Because you’ve SELECTed my heart.",
    "Are you a data warehouse? Because you’ve got all my information stored perfectly.",
    "Are you a data scientist? Because you know how to analyze my heart’s data.",
    "Are you a relational database? Because I want to join with you on a primary key.",
    "Are you SQL? Because you’re the language of my love queries.",
    "Are you a NoSQL database? Because you’re non-relat…, but I still want to relate to you.",
    "Are you a data dictionary? Because you define every aspect of my affection.",
    "Are you a data center? Because you’re the central focus of my attention.",
    "Are you a database administrator? Because you have…thority to grant access to my heart.",
    "Are you a table? Because I’d like to join you for a romantic dinner.",
    "Are you a backup? Because you’re my safety net in this unpredictable world.",
    "Are you a data packet? Because I’d like to transfer my feelings to you.",
    "Are you a database schema? Because you give structure to my love life.",
    "Are you SQL injection? Because every time I see you, you penetrate my defenses.",
    "Are you a foreign key? Because you’re the missing piece in my relational life.",
    "Are you ACID compliant? Because you bring stability to my emotional transactions.",
    "Are you a database index? Because you help me find what I’m looking for in love.",
    "Are you a deadlock? Because I feel stuck whenever I’m without you.",
    "Are you a clustered index? Because I want to be closely associated with you.",
    "Are you a database trigger? Because you always make my heart react.",
    "Are you a database query? Because you never fail to return zero results.",
    "Are you a database table? Because you’re so flat and uninteresting.",
    "Are you a primary key? Because you’re so essential yet so overused.",
    "Are you SQL? Because you always seem to lack the right syntax.",
    "Are you a NoSQL database? Because you’re so unstructured and chaotic.",
    "Are you a stored procedure? Because you’re as redundant as they come.",
    "Are you a data warehouse? Because you hold all my useless information.",
    "Are you a database index? Because you’re just an unnecessary extra layer.",
    "Are you a foreign key? Because you always seem to reference someone else.",
    "Are you a database administrator? Because you exce… making everything more complicated.",
    "Are you a transaction? Because you always leave me rolling back.",
    "Are you a data scientist? Because you never fail to overanalyze everything.",
    "Are you a backup? Because you’re just a safety net for when things inevitably go wrong.",
    "Are you a relational database? Because you always …o make everything about connections.",
    "Are you a SQL injection? Because you’re just full of malicious intent.",
    "Are you a deadlock? Because you always manage to bring everything to a standstill.",
    "Are you a data packet? Because you’re so small and insignificant.",
    "Are you a database schema? Because you’re just a rigid framework limiting my freedom.",
    "Are you ACID compliant? Because you’re so uptight and inflexible.",
    "Are you a clustered index? Because you’re just ano…y to make things needlessly complex.",
    "Are you a database? Because you’re the only one I want to join.",
    "Are you a SQL query? Because you’ve been running through my mind all day.",
    "Do you have a primary key? Because you’re the key to my heart.",
    "Are you a table? Because I’d like to create a relationship with you.",
    "Is your name SQL? Because you’re the answer to all my queries.",
    "Do you believe in love at first JOIN?",
    "Are you a NoSQL database? Because you make my heart skip a schema.",
    "Are you an index? Because you’ve just made my performance skyrocket.",
    "Is your name MongoDB? Because you’re so unstructured, and I’m drawn to you.",
    "Are you a backup? Because I’d be lost without you.",
    "Are you a stored procedure? Because you complete me.",
    "Is your database schema flexible? Because I’m open to anything with you.",
    "Are you a database administrator? Because you’ve just optimized my love life.",
    "Is your name Oracle? Because you’ve foreseen a future with me.",
    "Are you a query optimizer? Because you’ve just made my heart run faster.",
    "Are you a constraint? Because I can’t seem to escape your influence.",
    "Is your data encrypted? Because you’re so secure, it’s hard to get to know you.",
    "Are you a trigger? Because you make things happen in my heart.",
    "Is your name SQL Server? Because you’ve captured my attention.",
    "Are you a database backup? Because I want to keep you safe and sound.",
    "Are you a database query? Because my heart is SELECT-ed for you.",
    "Are you an SQL table? Because I can’t stop myself from joining with you.",
    "Is your name NoSQL? Because you’re making my heart skip a schema.",
    "Are you a data analyst? Because you just made my heart do a pivot.",
    "Do you believe in love at first database entry?",
    "Is your data encrypted? Because I can’t seem to decode your beauty.",
    "Are you a relational database? Because you complete my primary key.",
    "Do you have an index on your heart? Because I’m searching for a quick match.",
    "Are you a backup? Because I can’t imagine my life without you.",
    "Is your database schema normalized? Because you bring balance to my life.",
    "Are you a SQL injection? Because you’ve got my heart all vulnerable.",
    "Is your data structured? Because you give my life some order.",
    "Are you a data scientist? Because you’ve got the perfect formula for love.",
    "Do you have a transaction log? Because I want to commit to you.",
    "Are you a database administrator? Because you manage to keep my heart running smoothly.",
    "Is your love like a NoSQL database? Because it’s unstructured and amazing.",
    "Are you a foreign key? Because you’re the missing piece in my life.",
    "Is your database scalable? Because I see a lot of growth potential with you.",
    "Are you a query optimizer? Because you make everything run faster when you’re around.",
    "Is your love like Big Data? Because it’s too much to handle, but I can’t resist.",
    "Are you a database query? Because I can’t stop thinking about you.",
    "Are you a table? Because you’re well-structured and easy to query.",
    "Is your name SQL? Because you make my heart race with every command.",
    "Are you a foreign key? Because you complete me.",
    "Is your database encrypted? Because you’ve got my data locked up.",
    "Are you a NoSQL database? Because you’re unstructured, but I like it.",
    "Is your SQL statement a SELECT *? Because you’ve selected all of my attention.",
    "Are you a primary key? Because you’re the key to my heart.",
    "Is your database schema normalized? Because you’re the most organized person I know.",
    "Are you a database administrator? Because you manage to steal my thoughts all day.",
    "Is your data redundant? Because I can’t get enough of you.",
    "Are you a database backup? Because I feel safe when I’m with you.",
    "Is your database in the cloud? Because you’re always on my mind.",
    "Are you a SQL injection? Because you’ve penetrated my heart.",
    "Is your database ACID compliant? Because you make my transactions secure.",
    "Are you a clustered index? Because you bring order to my chaotic life.",
    "Is your database password protected? Because you’re my little secret.",
    "Are you a stored procedure? Because you always know how to handle me.",
    "Is your data integrity important to you? Because y…he most trustworthy person I’ve met.",
    "Are you a database table with a unique constraint?…ecause there’s no one else like you.",
    "Are you a database? Because I can’t stop querying for your love.",
    "Is your name SQL? Because you’ve been running through my mind all day.",
    "Are you a table? Because I’m ready to join you in a meaningful relationship.",
    "Is your password strong? Because you’ve got access to my heart.",
    "Do you have a schema? Because you’ve got the structure I’ve been looking for.",
    "Are you a NoSQL database? Because you’re unstructu…t I love the way you handle my data.",
    "Is your data encrypted? Because I can’t decode your beauty.",
    "Do you believe in relationships with foreign keys?…ecause I think we have a connection.",
    "Are you a SQL query? Because you’ve SELECT-ed my heart.",
    "Is your database optimized? Because you’ve just improved my love life.",
    "Are you a data scientist? Because you’ve got the algorithm to my heart.",
    "Is your data clean? Because you’ve filtered out all the other options.",
    "Are you a stored procedure? Because you’ve got me in a loop of love.",
    "Is your database scalable? Because I see a future where we grow together.",
    "Are you a backup? Because I’d be lost without you.",
    "Is your connection secure? Because I want to protect our love.",
    "Are you a SQL injection? Because you’ve injected happiness into my life.",
    "Is your database in the cloud? Because our love could reach new heights.",
    "Are you an index? Because you’ve sped up my heart rate.",
    "Is your data reliable? Because I can count on you.",
    "Are you a Wi-Fi signal? Because I’m feeling a strong connection.",
    "Do you have a map? I keep getting lost in your profile pictures.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Do you believe in love at first swipe?",
    "Are you a campfire? Because you’re hot and I want s’more.",
    "Do you have a name, or can I call you mine?",
    "Are you a bank loan? Because you have my interest.",
    "Is your name Netflix? Because I could binge-watch your photos all day.",
    "If you were a vegetable, you’d be a cute-cumber!",
    "Do you have a sunburn, or are you always this hot?",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Is your dad a baker? Because you’re a cutie pie.",
    "Are you French? Because Eiffel for you.",
    "Do you have a name, or can I call you mine?",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Is your name Wi-Fi? Because I’m really feeling a connection.",
    "Do you have a map? Because I just got lost in your profile pics.",
    "Is your name Google? Because you’ve got everything I’ve been searching for.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is your name Ariel? Because we mermaid for each other.",
    "Are you a database query? Because I can’t stop thinking about you.",
    "Are you a SQL table? Because I’m ready to join our hearts together.",
    "You must be a database administrator because you’ve got me indexing my thoughts on you.",
    "Are you a NoSQL database? Because you’re unstructured, but I can’t resist you.",
    "Is your name SQL? Because you’ve been running through my mind all day.",
    "Are you a database backup? Because I never want to lose you.",
    "If we were records in a database, our relationship status would be set to “committed.”",
    "Do you have a primary key? Because you’re the key to my heart.",
    "Are you SQL? Because you make my heart race with every query.",
    "Is your name MongoDB? Because you make my heart skip a beat, and it’s not just NoSQL.",
    "Are you a data scientist? Because I’d love to explore the depths of your data.",
    "Is your database schema flexible? Because I can see us fitting together perfectly.",
    "Are you a data warehouse? Because I want to store all my memories with you.",
    "If our love were a transaction, it would be ACID-c…ways Committed to Infinite Devotion.",
    "Are you a big data analyst? Because you’ve analyzed my heart and found a perfect match.",
    "Is your database encrypted? Because you’re a secret I’m eager to uncover.",
    "Are you a data center? Because you’re where all my thoughts and feelings converge.",
    "Are you SQL Server? Because you make my heart Microsoft a beat.",
    "Is your love like a NoSQL database? Because it’s unstructured but full of surprises.",
    "Are you a relational database? Because I feel a strong connection with you.",
    "Are you a database query? Because I can’t stop thinking about you.",
    "Is your name SQL? Because you make my heart race with your queries.",
    "Are you a table? Because I’d like to join you.",
    "You must be a database administrator because you’ve got my SQL.",
    "Is your data encrypted? Because I want to decode your heart.",
    "Are you a NoSQL database? Because you’re so unstructured, yet I can’t resist you.",
    "Are you a foreign key? Because you complete me.",
    "Is your name MongoDB? Because I’d love to store my feelings in you.",
    "Are you a primary key? Because you’re the key to my heart.",
    "Do you believe in love at first query?",
    "Are you an index? Because you’ve just made my performance improve.",
    "Is your database schema flexible? Because I can see us fitting together perfectly.",
    "Are you a stored procedure? Because you’re always there when I need you.",
    "Is your data well-organized? Because you’ve sorted out my chaotic life.",
    "Are you a relational database? Because our connection is strong.",
    "Is your database normalized? Because I can’t stand redundancy, but I love you.",
    "Are you a backup? Because I’d be lost without you.",
    "Is your SQL code well-commented? Because I can’t stop reading between the lines.",
    "Are you a deadlock? Because I can’t escape your embrace.",
    "Is your database ACID compliant? Because you’re ev…, Consistent, Isolated, and Durable.",
    "Are you a database query? Because I’m drawn to your data.",
    "Are you SQL? Because you complete my queries.",
    "Are you a table? Because you’ve got all the right attributes.",
    "Are you a foreign key? Because you make my heart referential.",
    "Is your name NoSQL? Because you’re so unstructured, yet I can’t resist you.",
    "Are you a primary key? Because you’re the key to my heart.",
    "Is your name Oracle? Because you’re the answer to all my questions.",
    "Are you MongoDB? Because you store all my love documents.",
    "Are you a schema? Because you define the structure of my dreams.",
    "Are you MySQL? Because you’ve got me hooked on your relationship.",
    "Is your name SQL Server? Because you’ve got my data under control.",
    "Are you a backup? Because I’ll always be there to restore you.",
    "Are you a transaction? Because you make my heart commit.",
    "Is your name Redis? Because I can’t forget about you.",
    "Are you a cursor? Because you’ve got me iterating through thoughts of you.",
    "Is your name Index? Because you’ve improved the performance of my life.",
    "Are you a query optimizer? Because you’ve optimized my feelings for you.",
    "Is your name PostgreSQL? Because you’ve captured my heart in a relational way.",
    "Are you a data analyst? Because you’ve analyzed your way into my heart.",
    "Are you a database administrator? Because you’re the master of my data.",
    "Are you a database? Because you’re the key to my heart.",
    "Are you SQL? Because you’ve just entered my query and I can’t wait to get the result.",
    "Do you have a relational model? Because I feel a connection.",
    "Is your name NoSQL? Because you’re definitely not like the others.",
    "Are you an index? Because you’ve optimized my life.",
    "Are you MongoDB? Because you make my heart skip a JSON.",
    "Is your database schema flexible? Because I’d like to add you to my life.",
    "Are you Oracle? Because you’ve got the keys to my future.",
    "Do you believe in data integrity? Because I promis…to keep our relationship consistent.",
    "Are you a DBA? Because you manage to keep my heart running smoothly.",
    "Is your SQL statement prepared? Because you’ve got my full attention.",
    "Are you MySQL? Because I want you to be the SQL to my PHP.",
    "Do you like joins? Because together, we can create some beautiful relationships.",
    "Is your database encrypted? Because you’re the secret I’ve been searching for.",
    "Are you a query? Because you’ve just SELECT-ed my interest.",
    "Do you have a primary key? Because you’re the most important thing in my life.",
    "Is your database open source? Because I’m ready to commit to you.",
    "Are you SQL Server? Because you’ve just sparked a new connection.",
    "Do you believe in backups? Because I’d hate to lose you.",
    "Are you Hadoop? Because you’ve got me distributed.",
  ],
  programmer: [
    "Are you a JavaScript Promise? Because you look like you'll resolve all my problems.",
    "Is your name Wi-Fi? Because I'm feeling a strong connection.",
    "While (true) { ilove(you); }",
    "You must be a function, because I keep calling you and can't get enough.",
    "Are you a CSS rule? Because you've got great class.",
    "Are you a computer algorithm? Because you’ve just sorted yourself into my heart.",
    "Is your name Google? Because you’ve got everything I’ve been searching for.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Are you a keyboard? Because you’re my type.",
    "Is your name Wi-fi? Because I’m feeling a connection.",
    "Are you a software update? Because not a day goes by without me thinking about you.",
    "Are you a computer virus? Because you’ve infected my heart.",
    "Is your name Java? Because you’ve got the key to my heart.",
    "Are you a computer monitor? Because whenever I see you, my heart rate increases.",
    "Is your name File? Because you keep popping up in my life.",
    "Are you a CAPTCHA? Because you’re making my heart race with these twists and turns.",
    "Is your name Bluetooth? Because I’m feeling a wireless connection between us.",
    "Are you a graphics card? Because you make my heart render in 4K.",
    "Is your name RAM? Because you’ve got my memory all occupied.",
    "Are you a firewall? Because you’ve just blocked all other potential matches.",
    "Is your name HTML? Because you’ve got my heart in tags.",
    "Are you a cursor? Because you’re always pointing in the right direction—towards you.",
    "Is your name Linux? Because you’ve just made my heart open source.",
    "Are you a computer mouse? Because you’ve clicked with me from the start.",
    "Is your name Python? Because my heart is coding in the language of love for you.",
    "Are you a computer program? Because my heart just encountered an unexpected error, and I need your input to debug it.",
    "Are you Wi-Fi? Because I’m feeling a strong connection and hoping it’s not just a one-time password.",
    "Is your name Google? Because you’ve got everything I’ve been searching for.",
    "Are you a keyboard? Because you’re definitely my type.",
    "Are you an algorithm? Because you’ve sorted yourself right into my heart.",
    "Is your name JavaScript? Because you make my heart function asynchronously.",
    "Are you a computer virus? Because you’ve infected my thoughts, and I can’t stop thinking about you.",
    "Is your name RAM? Because you’ve got my memory working in overdrive.",
    "Are you a file compression algorithm? Because you just made my heart skip a ZIP.",
    "Is your name Java? Because you’ve got me caught in an endless loop of love.",
    "Are you a firewall? Because you’ve blocked all other thoughts from my mind.",
    "Is your name Linux? Because you’ve got my heart running on open source feelings.",
    "Are you a computer screen? Because every time I see you, I light up with joy.",
    "Is your name Excel? Because you’ve just calculated the perfect formula for my happiness.",
    "Are you a USB drive? Because you’ve just transferred my emotions to a whole new level.",
    "Is your name Python? Because you’ve wrapped yourself around my heart with elegance.",
    "Are you a software update? Because meeting you feels like an essential upgrade in my life.",
    "Is your name HTML? Because you’ve structured my feelings in a way I never thought possible.",
    "Are you a database? Because you’ve just stored yourself permanently in my heart.",
    "Is your name Windows? Because every time I look at you, I feel like I’ve just upgraded to a better version of life.",
    "Are you a computer keyboard? Because you’re my type.",
    "Are you a software update? Because not being with you feels like a bug in my system.",
    "Are you a Wi-Fi signal? Because I’m feeling a strong connection.",
    "Is your name Google? Because you’ve got everything I’ve been searching for.",
    "Are you a firewall? Because you’ve just blocked all unauthorized access to my heart.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Is your name Bluetooth? Because I’m feeling a wireless connection.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Is your name Java? Because you’ve got the key to my heart.",
    "Are you a computer mouse? Because you’ve been running through my mind all day.",
    "Are you a file format? Because you just made my heart skip a beat.",
    "Is your name HTML? Because you’ve got the structure to my emotions.",
    "Are you a password? Because you’re hard to forget.",
    "Is your name Linux? Because you’ve just gained root access to my heart.",
    "Are you an algorithm? Because you’ve solved the equation of my loneliness.",
    "Is your name Ctrl? Because you’ve got control over my heart.",
    "Are you a variable? Because you just changed my life’s value.",
    "Is your name Siri? Because you make everything better.",
    "Are you a code compiler? Because you make my heart syntax error-free.",
    "Is your name Python? Because you’ve wrapped yourself around my thoughts.",
    "Are you a computer program? Because you’ve just executed a perfect “Ctrl+X” on my heart.",
    "Are you a Wi-Fi signal? Because I’m feeling a strong connection.",
    "If you were a browser, you’d be called Firefoxy.",
    "Is your name Google? Because you’ve got everything I’ve been searching for.",
    "Are you a computer keyboard? Because you’re my type.",
    "Do you believe in love at first sight, or should I refresh my browser?",
    "Are you an algorithm? Because you’ve sorted yourself right into my heart.",
    "Is your name Wi-fi? Because I’m really feeling a connection.",
    "If beauty were time, you’d be an eternity loop.",
    "Are you a computer virus? Because you just infected my heart.",
    "Do you have a map? I keep getting lost in your eyes.sys.",
    "Are you a software update? Because not a day goes by without me thinking about you.",
    "Is your name Bluetooth? Because I’m feeling a wireless connection.",
    "Are you a code snippet? Because you’ve just stolen a piece of my heart.",
    "Is your name Google Chrome? Because you’ve got everything I’ve been browsing for.",
    "Are you an AI? Because you just upgraded my feelings to the next level.",
    "If you were a file format, you’d be a JPEG – jolly, enticing, and pretty gorgeous.",
    "Are you a software developer? Because you’ve just compiled all my feelings.",
    "Do you have a name, or can I call you mine.exe?",
    "Are you a computer mouse? Because you’ve clicked something in me.",
    "Are you a computer? Because you’ve got my heart processing at maximum speed.",
    "Are you a keyboard? Because you’re just my type.",
    "Is your name Google? Because you’ve got everything I’ve been searching for.",
    "Are you a software update? Because not being with you feels like a major bug.",
    "Is your name Wi-fi? Because I’m feeling a strong connection.",
    "Are you an algorithm? Because you’ve sorted out my feelings in the most efficient way.",
    "Is your name Java? Because you’ve got the write class.",
    "Are you a firewall? Because you’ve just blocked all other potential matches.",
    "Is your name RAM? Because you make my heart speed up.",
    "Are you a file compression algorithm? Because you just took my breath away and reduced it to a zip.",
    "Is your name Dropbox? Because you make my heart sync with happiness.",
    "Are you a computer virus? Because you’ve infected my heart.",
    "Is your name HTML? Because you’ve got everything I’ve been looking for in a mate.",
    "Are you a screen saver? Because you’ve been running through my mind all day.",
    "Is your name JavaScript? Because you make my heart race asynchronously.",
    "Are you a GPU? Because you make my graphics card overheat.",
    "Is your name Excel? Because you’ve just calculated the formula to my heart.",
    "Are you a command prompt? Because you’ve got total control over my feelings.",
    "Is your name Linux? Because you’ve just open-sourced my heart.",
    "Are you a CAPTCHA? Because you’ve got me typing in my feelings.",
    "Are you a software update? Because my heart is telling me it’s time to install you in my life.",
    "Are you a Wi-Fi signal? Because I’m feeling a strong connection.",
    "Are you a keyboard? Because you’re my type.",
    "Are you a computer program? Because you’ve just executed a perfect loop in my mind.",
    "Are you an algorithm? Because you’ve sorted yourself into my heart.",
    "Are you a firewall? Because you’ve blocked all other thoughts from my mind.",
    "Are you a hard drive? Because you’ve got a lot of storage in my heart.",
    "Are you a variable? Because you’re the constant in my ever-changing life.",
    "Are you a GPU? Because you’ve accelerated the processing speed of my heartbeat.",
    "Are you a coding language? Because you’ve got the syntax to my heart.",
    "Are you a CAPTCHA? Because my heart can’t seem to solve the puzzle of your beauty.",
    "Are you a cursor? Because wherever you go, you always leave a lasting impression.",
    "Are you a quantum computer? Because you’ve entangled my feelings in a superposition of love.",
    "Are you an error message? Because you’ve just disrupted the normal flow of my thoughts.",
    "Are you a pixel? Because you’ve added color to the monochrome screen of my life.",
    "Are you a cloud service? Because you’ve made my heart migrate to the happiness server.",
    "Are you an API? Because I want to connect to you and access all your love functions.",
    "Are you a motherboard? Because you’re the foundation of my affection.",
    "Are you a browser? Because you’ve just navigated your way into my heart’s bookmarks.",
    "Are you a recursive function? Because I can’t seem to escape the thought of you.",
    "Are you a database query? Because my heart is searching for a perfect match.",
    "Are you a function call? Because I can’t resist the urge to execute you.",
    "Are you a compiler? Because you make my heart go from source code to object file.",
    "Are you an IDE? Because I feel most productive when you’re open.",
    "Are you a semaphore? Because you’ve signaled my heart to start a romantic process.",
    "Are you a distributed system? Because my affection for you spans across multiple nodes.",
    "Are you a CSS file? Because you’ve styled my world with beauty and elegance.",
    "Are you a code review? Because I can’t help but give you my unconditional approval.",
    "Are you a JSON object? Because you’ve encapsulated all my feelings in a well-structured manner.",
    "Are you a virtual machine? Because you’ve managed to run in my mind all day long.",
    "Are you an antivirus? Because you’ve protected my heart from all the emotional malware.",
    "Are you an encryption algorithm? Because you’ve encoded your love into my heart securely.",
    "Are you a command prompt? Because you’ve got the authority to control my emotions.",
    "Are you a boolean? Because meeting you feels like a true or false moment in my life.",
    "Are you a software bug? Because you’ve just caused a system crash in my heart.",
    "Are you a git repository? Because I want to commit to you for a lifetime.",
    "Are you a CSS selector? Because you’ve selected my heart with perfect specificity.",
    "Are you an API endpoint? Because you’re the destination for all my romantic requests.",
    "Are you a quantum entanglement? Because our connection transcends the boundaries of space and time.",
    "Are you a command-line interface? Because every input from you generates a lovely output in my heart.",
    "Are you a computer keyboard? Because you’re my type!",
    "Are you Wi-Fi? Because I’m really feeling a connection.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a computer program? Because you’ve just executed a major system error in my heart.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Do you believe in love at first byte?",
    "Are you a software update? Because not having you in my life is a bug I need to fix.",
    "Are you an algorithm? Because you keep running through my mind.",
    "Is your name Bluetooth? Because I’m feeling a strong connection.",
    "If you were a web browser, you’d be called Firefoxy.",
    "Do you have 11 protons? Because you’re sodium fine!",
    "Are you a computer mouse? Because you’ve been running through my mind all day.",
    "You must be a keyboard, because you’re just my type.",
    "Are you a computer? Because you’ve got my hardware malfunctioning.",
    "Do you have a name, or can I call you mine?",
    "Are you a computer scientist? Because you’ve just compiled a list of reasons to date you.",
    "Is your name Wi-Fi? Because I’m really feeling a connection.",
    "Can you be my private variable? I want to change your value, but only for myself.",
    "Are you a computer virus? Because you’ve infected my heart.",
    "Are you a computer? Because my love for you is 01010011 01010101 01010000 01000101 01010010.",
    "Are you Wi-Fi? Because I’m feeling a connection.",
    "Are you a keyboard? Because you’re just my type.",
    "Are you a software update? Because not having you is a security risk.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a computer virus? Because you’ve infected my heart.",
    "Are you an algorithm? Because you’ve solved the equation of my heart.",
    "Are you a Mac? Because you’re sleek, stylish, and I can’t resist you.",
    "Is your name Windows? Because you’ve made my life pop up with happiness.",
    "Are you a firewall? Because you’ve got my heart on lockdown.",
    "Is your Wi-Fi open? Because I’m ready to connect with you.",
    "Are you a software developer? Because you make my heart race with every line of code.",
    "Are you Java? Because you make my heart “NullPointerException.”",
    "Is your name Dropbox? Because you keep all my love notes safe in the cloud.",
    "Are you a browser? Because you’ve opened up a world of possibilities for me.",
    "Are you a cache? Because you’ve stored yourself in my memory forever.",
    "Is your name Ctrl+Alt+Delete? Because you’re the only thing that can restart my heart.",
    "Are you a mouse? Because you’ve clicked with me from the first moment we met.",
    "Is your heart a hard drive? Because I want to back up all my love on it.",
    "Are you a computer screen? Because I can’t take my eyes off you.",
    "Are you a computer keyboard? Because you’re just my type.",
    "Are you a Wi-Fi signal? Because I’m feeling a strong connection.",
    "Do you have a map? Because I just got lost in your eyes.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Is your Wi-Fi password “loveyou”? Because I’ve been trying to connect with you all day.",
    "Are you a computer program? Because you’ve got me stuck in an infinite loop of love.",
    "Are you a software update? Because not a day goes by that I don’t want you.",
    "Is your name Bluetooth? Because I’m feeling a strong connection.",
    "Do you have a name, or can I call you mine?",
    "Is your name Wi-Fi? Because I’m really feeling a connection.",
    "If you were a triangle, you’d be acute one.",
    "Are you an algorithm? Because I’ve been searching for someone like you my whole life.",
    "Is your dad a software developer? Because you’re definitely a program I’d like to install.",
    "Are you a computer mouse? Because you make my heart click.",
    "Do you have a mirror in your pocket? Because I can see myself in your pants.",
    "Is your name HTML? Because you’re perfectly formatted.",
    "Are you a firewall? Because you’ve got my heart on lockdown.",
    "Is your name RAM? Because you’re making my heart race.",
    "Are you a computer virus? Because you’ve infected my heart.",
    "Are you a computer keyboard? Because you’re my type.",
    "Is your name Wi-Fi? Because I’m feeling a strong connection.",
    "Are you a software update? Because not being with you feels like a bug in my system.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a computer mouse? Because you make my heart click.",
    "If you were a function, you’d be called ‘irresistible.’",
    "Are you a computer virus? Because you’ve infected my heart.",
    "Is your Wi-Fi password “hello”? Because when I saw you, my heart said, “That’s the one.”",
    "Can you help me troubleshoot my love life? It seems to be crashing when you’re not around.",
    "Is your name Ctrl+Alt+Delete? Because you’ve got my heart stuck in a loop.",
    "Are you a computer program? Because you’ve just executed the “sweep me off my feet” command.",
    "Is your name Java? Because you’re steaming hot and full of energy.",
    "Are you an antivirus software? Because you’re scanning my heart for malware.",
    "Is your Wi-Fi signal strong? Because I’m feeling a strong connection with you.",
    "Are you a keyboard shortcut? Because you’re making my heart skip a beat.",
    "Is your name HTML? Because you’re the foundation of my web of dreams.",
    "Are you a computer graphics card? Because you make my heart race with high performance.",
    "Is your name Bluetooth? Because you’re always on my mind, wirelessly.",
    "Do you believe in love at first swipe? Because I think we just matched perfectly.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a computer keyboard? Because you’re my type.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Are you a Wi-Fi signal? Because I’m feeling a strong connection.",
    "Do you believe in love at first byte, or should I refresh my cache?",
    "Is your name Wi-Fi? Because I’m really feeling a connection.",
    "Are you an algorithm? Because I’ve been searching for you all my life.",
    "Can you be my private variable? I want to make sure you’re always in my scope.",
    "Is your dad a programmer? Because you’re a masterPIEce.",
    "Do you have a mirror in your pocket? Because I can see myself in your pants.",
    "Are you a software update? Because not a day goes by without me thinking about you.",
    "Is your name Mac? Because you’re the apple of my eye.",
    "Are you JavaScript? Because you make everything on this page beautiful.",
    "Is your name Ctrl+Alt+Del? Because you have the power to restart my heart.",
    "Are you a computer monitor? Because I can’t take my eyes off you.",
    "Do you have 11 protons? Because you’re sodium fine.",
    "Is your name Bluetooth? Because I’m feeling a strong wireless connection.",
    "Are you a file transfer? Because I want to drag and drop into your life.",
    "Is your name Java? Because you’ve got me in the “Hello World” of emotions.",
    "Are you a computer keyboard? Because you’re my type.",
    "Are you Wi-Fi? Because I’m really feeling a connection.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Do you have a map? I just got lost in your web browser.",
    "Are you a software update? Because not a day goes by without me thinking about you.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a computer virus? Because you’ve infected my heart.",
    "Is your name Wi-Fi? Because I’m really feeling a strong signal with you.",
    "Are you an algorithm? Because I’d love to explore your data.",
    "Do you believe in love at first byte, or should I send you a second message?",
    "Is your name Ctrl+C? Because you’ve just copied my heart.",
    "Are you a computer monitor? Because you’re keeping me up all night.",
    "Do you have a floppy disk? Because your smile is just so magnetic.",
    "Is your name Java? Because you make my heart race.",
    "Are you a computer mouse? Because you’ve been running through my mind all day.",
    "Is your name RAM? Because you’re making my heart race.",
    "Are you an antivirus program? Because you’ve just swept me off my feet.",
    "Do you have a USB port? Because I want to plug into your world.",
    "Is your name Microsoft Excel? Because you have a lot of attractive features.",
    "Are you a computer? Because you’re rebooting my love life.",
    "Are you a computer keyboard? Because you’re my type.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Are you Wi-Fi? Because I’m really feeling a connection.",
    "Are you a software update? Because not a day goes by without me thinking about you.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a computer scientist? Because you’ve just encrypted my heart.",
    "Do you have a map? Because I just got lost in your eyes.",
    "Are you a computer virus? Because you’ve infected my heart.",
    "Are you Java? Because you’re hot and I can’t stop coding for you.",
    "Do you have a name, or can I call you mine?",
    "Is your name Wi-Fi? Because I’m really feeling a connection.",
    "Are you a file format? Because you’ve got everything in the right place.",
    "Are you a computer mouse? Because you’ve been running through my mind all day.",
    "Are you an app? Because you make my heart race.",
    "Do you have a mirror in your pocket? Because I can see myself in your pants.",
    "Are you a computer monitor? Because you’re always on my mind.",
    "Is your name Ctrl+Alt+Delete? Because you have my heart locked up.",
    "Are you a web browser? Because you’ve got me surfing through emotions.",
    "Are you a computer? Because you’re the hardware to my software.",
    "Is your name CAPS LOCK? Because you’re always yelling into my heart.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Are you a computer keyboard? Because you’re my type.",
    "Is your name Wi-Fi? Because I’m really feeling a connection.",
    "Are you a software update? Because not being with you is a bug in my system.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a computer monitor? Because you’re always on my mind.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Are you a firewall? Because you’ve got my heart on lockdown.",
    "Is your name Bluetooth? Because I’m feeling a wireless connection.",
    "Are you an algorithm? Because you keep running through my mind.",
    "Is your name RAM? Because you’re always on my memory.",
    "Are you an HTML file? Because you’ve got everything I’m looking for.",
    "Is your name Java? Because you’ve got class.",
    "Are you a computer mouse? Because you’ve just clicked with me.",
    "Is your name Linux? Because I find you open and refreshing.",
    "Are you a computer virus? Because you’ve infected my heart.",
    "Is your name Ctrl+C? Because you’ve copied my heart.",
    "Are you a screen saver? Because you’ve been running through my mind all day.",
    "Is your name Windows? Because you’ve got my heart in a spin.",
    "Are you a hard drive? Because you’ve got a lot of space for my love.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Are you a keyboard? Because you’re just my type.",
    "Are you Wi-Fi? Because I’m really feeling a connection.",
    "Are you a computer whiz? Because you’ve got my hard drive all worked up.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a software update? Because not a day goes by without me thinking about you.",
    "Is your Wi-Fi signal strong? Because I’m feeling a strong connection here.",
    "Are you a computer program? Because you just made my heart execute a perfect loop.",
    "Is your name RAM? Because you’re making my heart race.",
    "Are you a computer mouse? Because you’ve got me clicking with excitement.",
    "Are you Java? Because you make my heart race without any garbage collection.",
    "Is your name Ctrl? Because you’ve got control over my heart.",
    "Are you a computer virus? Because you’ve infected my heart.",
    "Is your name Windows? Because you’ve opened up a window to my heart.",
    "Are you a browser? Because you’ve just opened up a world of possibilities for me.",
    "Is your name Linux? Because you’ve got me feeling open-source love.",
    "Are you a computer monitor? Because I can’t take my eyes off you.",
    "Is your name Python? Because you’ve wrapped yourself around my heart.",
    "Are you SQL? Because you’ve just made my heart database.",
    "Is your name HTML? Because you’ve structured my world.",
    "Are you a computer program? Because you’ve got my heart stuck in an infinite loop.",
    "Are you a keyboard? Because you’re my type.",
    "Are you Wi-Fi? Because I’m feeling a connection.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Do you have a map? I just got lost in your eyes.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Is your name Bluetooth? Because I’m feeling a connection.",
    "Are you a computer virus? Because you’ve infected my heart.",
    "Is your name Windows? Because you’ve made my life pop up with meaning.",
    "Are you a software update? Because not a day goes by without me thinking about you.",
    "Do you believe in love at first website?",
    "Are you an algorithm? Because I think we have great chemistry.",
    "Are you JavaScript? Because you make my heart race.",
    "Are you a keyboard shortcut? Because you just made my heart skip a beat.",
    "Is your name HTML? Because you’re the foundation of everything I desire.",
    "Are you a CAPTCHA? Because you’re hard to figure out, but I’m determined to prove I’m not a robot.",
    "Is your name Linux? Because you’ve got my heart in command.",
    "Are you a browser? Because you’ve opened up a world of possibilities for me.",
    "Is your name Java? Because you’ve got me feeling like I’m in love with coffee.",
    "Are you a computer monitor? Because you brighten up my day.",
    "220+ Steel-tingling Pick Up Lines: Forge a Connection with Metallic Charm!",
    "“380+ Database Pick-Up Lines: Flirting with SQL and Finding Love in Data”",
    "“380+ Quality Pick-Up Lines: Elevate Your Flirting Game with Style!”",
    "“380+ Textbook Pick-Up Lines: Educate Your Love Life!”",
    "“380+ Calculated Pick-Up Lines: When Math Meets Romance in Unexpected Ways!”",
    "If they made you in C, you would have a pointer to my heart!",
    "let me be your CSS to your HTML",
    "Fork my heart because I'm ready to commit",
    "I’ve spent so much time working with computers, you bet I know how to turn things on",
    "I must be an exception because you have sure caught me.",
    "Are you a double? The thought of you always floats inside my head.",
    "Hey girl did u lose a timestamp coz i am pretty sure its DateTime.now();",
    '"Date me because I have side projects instead of side chicks"',
    "If I pull and push it in, know that I am already committing.",
    "with all the variables in life...baby can you be my constant...",
    "Are you https?? Bcz without you I'm just ://",
    "Are you a function? Let me call you.",
    "Girl are you CSS? Cause you got class",
    "It works on my end",
    "We can merge, without conflicts!",
    "Are you a keyboard, cause you're my type",
    "May I append my surname to your name?",
    "You are my bug in my code coz i spend all my time on you",
    "My object is oriented towards you.",
    "Are you an exception? Let me catch you.",
    "Are you a semicolon, because you totally completing me!",
    "Can you be my html because i will give my body to you",
    "You are my number 0",
    "Me += You",
    "Are you double? You always float inside my head.",
    "I can't wait to inject my SQL into your application layer.",
    "I always forget ; because I want to end it with you",
    "Hello, Girl!",
  ],
};
